siteName: Blog
description: this is a blog
baseurl: http://localhost/php-site-maker
sourcedir: _source
indexPostsNum: 5
disqusId:
htmldir: ../
path:
	page: ./_source/page/
	post: ./_source/post/
	make: ./_make/
	layout: ./_template/
	blog: ./blog/
	olderPage: ./blog/page/
