siteName: psm
description: this is a website
baseurl: http://localhost/php-site-maker/
baseurl: http://klml.lynx.uberspace.de/dev/php-site-maker/
sourcedir: _source
indexPostsNum: 5
disqusId:
htmldir: ../
htmlextension: .html
htmlextension: 
sourcedir: ../_source/
sourceextension: md
pagedurable: ../_source/_pagedurable.md
path:
	page: ../_source/page/
	make: ../_make/
	layout: ../_template/

---
layout: page
title: Title from root-config 
comment: false
description: Some general site wide description
