siteName: Blog
description: this is a website
baseurl: http://localhost/php-site-maker
sourcedir: _source
indexPostsNum: 5
disqusId:
htmldir: ../
sourcedir: ../_source/
path:
	page: ./_source/page/
	make: ./_make/
	layout: ./_template/
